require 'rubygems'
require 'bundler'
begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end
require 'rake'

BOOTSTRAP_CSS = "../css/bootstrap.css"
BOOTSTRAP_MIN_CSS = "../css/bootstrap.min.css"
BOOTSTRAP_RESPONSIVE_CSS = "../css/bootstrap-responsive.css"
BOOTSTRAP_RESPONSIVE_MIN_CSS = "../css/bootstrap-responsive.min.css"
GATHERER_CSS = "../css/main.css"
GATHERER_MIN_CSS = "../css/main.css" #no .min in name for html5boilerplate build script

#debug-info to get source maps
SASS_COMMAND = "sass --precision 16 --load-path lib --debug-info --style"
SASS_COMMAND_PROD = "sass --precision 16 --load-path lib --style" #no source maps info

task BOOTSTRAP_CSS do |target|
  sh "#{SASS_COMMAND} expanded lib/bootstrap.scss:#{target}"
  css = IO.read(target.to_s)
  css.gsub!('@DATE', `date`.strip)
  File.open(target.to_s, 'w+') { |f| f.write(css) }
end

task BOOTSTRAP_MIN_CSS do |target|
  sh "#{SASS_COMMAND_PROD} compressed lib/bootstrap.scss:#{target}"
end


task BOOTSTRAP_RESPONSIVE_CSS do |target|
  sh "#{SASS_COMMAND} expanded lib/responsive.scss:#{target}"
  css = IO.read(target.to_s)
  css.gsub!('@DATE', `date`.strip)
  File.open(target.to_s, 'w+') { |f| f.write(css) }
end

task BOOTSTRAP_RESPONSIVE_MIN_CSS do |target|
  sh "#{SASS_COMMAND_PROD} compressed lib/responsive.scss:#{target}"
end

task GATHERER_CSS do |target|
  sh "#{SASS_COMMAND} expanded lib/gatherer.scss:#{target}"
  css = IO.read(target.to_s)
  css.gsub!('@DATE', `date`.strip)
  File.open(target.to_s, 'w+') { |f| f.write(css) }
end

task GATHERER_MIN_CSS do |target|
  sh "#{SASS_COMMAND_PROD} compressed lib/gatherer.scss:#{target}"
end

desc "build regular and compresed versions of bootstrap"
#task :build => [BOOTSTRAP_MIN_CSS, BOOTSTRAP_RESPONSIVE_MIN_CSS, GATHERER_MIN_CSS]
task :build => [GATHERER_MIN_CSS]

desc "rebuild regular version of bootstrap when modifications are made"
task :watch do
  #sh "#{SASS_COMMAND} expanded --watch lib/bootstrap.scss:#{BOOTSTRAP_CSS} lib/responsive.scss:#{BOOTSTRAP_RESPONSIVE_CSS} lib/gatherer.scss:#{GATHERER_CSS}"
  sh "#{SASS_COMMAND} expanded --watch lib/gatherer.scss:#{GATHERER_CSS}"
end

task :default => :build
